# Generated by Django 2.0.5 on 2018-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_auto_20180515_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
