# Generated by Django 2.0.5 on 2018-05-16 09:04

from django.db import migrations, models
import task_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_user_fav_color'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', task_management.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='fav_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
