# Generated by Django 2.0.5 on 2018-05-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_auto_20180516_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_verication',
            field=models.BooleanField(default=False),
        ),
    ]
