# Generated by Django 2.0.5 on 2018-05-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_user_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_login',
            table='user_login',
        ),
    ]
