# Generated by Django 2.0.5 on 2018-05-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0008_auto_20180517_0929'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_login',
            table='User_login',
        ),
    ]
