# Generated by Django 2.0.5 on 2018-05-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0010_user_login_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
