# Generated by Django 2.0.5 on 2018-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0011_auto_20180518_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'complete'), ('INPROGRESS', 'Inprogress'), ('IDLE', 'Idle')], default='Idle', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'complete'), ('INPROGRESS', 'Inprogress'), ('IDLE', 'Idle')], default='Idle', max_length=10),
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
