# Generated by Django 2.0.5 on 2018-05-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0013_auto_20180518_0940'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
    ]
