# Generated by Django 2.0.5 on 2018-05-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0014_auto_20180521_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_date',
            new_name='target_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
    ]
